dominodatalab/domino-data

- Makefile
- pyproject.toml
- requirements.txt
- scripts/gen.py
Fix Dependabot alerts and type hinting issues
> Cleanup requirements.txt and codestyle

- tests/cassettes/test_trainingset/test_create_duplicate_name_error.yaml
- tests/test_trainingset.py
Unit test needed for duplicate training set created in a different project with same name
https://dominodatalab.atlassian.net/browse/DOM-36662
- [ x ] Test
> Unit test for duplicate training set creation in another project

- domino_data/featurestore.py
- feature_store_api_client/api/default/get_feature_view_name_store.py
- openapi/featurestore.yaml
- poetry.lock
Consumption flow CLI that takes the stored feature store metadata files out of the S3 bucket associated with the feature store and creates a new directory and populates with the files.
```from feast import FeatureStore
store = FeatureStore(repo_path=".")
store.list_feature_views()```
- [ X] 🚀 New feature (non-breaking change which adds functionality)
> Consumption flow CLI

- datasource_api_client/models/list_request.py
- domino_data/data_sources.py
- openapi/datasource.yaml
- tests/cassettes/test_datasource/test_client_list_keys_in_object_store.yaml
- tests/test_datasource.py
Feature request: Page size add to get keys
Tested manually
https://dominodatalab.atlassian.net/browse/DOM-40225
https://github.com/cerebrotech/datasource-proxy/pull/126
> [DOM-40225] Add page size param to get keys

- pyproject.toml
Bump to version 0.5.0 for Domino Release 5.4.0
https://dominodatalab.atlassian.net/browse/RM-1822
> Bump to 0.5.0

- domino_data/logging.py
Allow console logging only for feature store
https://dominodatalab.atlassian.net/browse/DOM-42243
> Added filter for console logging

- pyproject.toml
Bumped up the version
https://dominodatalab.atlassian.net/browse/DOM-43059
> Bumped up the version

- .gitmodules
- pyproject.toml
Prepare for 5.7.0 release
https://dominodatalab.atlassian.net/browse/RM-2371
> Update to 5.7.0

- poetry.lock
- pyproject.toml
Update package dependencies
N/A
> Update dependencies to use arrow 10.0.0

- domino_data/data_sources.py
- tests/test_datasource.py
Improved error log message
https://dominodatalab.atlassian.net/browse/DOM-48640
> improved error message

- domino_data/configuration_gen.py
Added db2 config
https://dominodatalab.atlassian.net/browse/DOM-48882
> Added missing db2 config

- pyproject.toml
Update source of truth after merging in changes for example catalog code
> Update source of truth for SDK

- pyproject.toml
> 5.7.2 PyProject Version Bump

- pyproject.toml
Update the Python SDK version to 5.8.0dev6 for the next dev release.
> Update Python SDK version

- pyproject.toml
Update dev version of Python SDK for next publish to 5.8dev7
> [DOM-50210] Update Next Dev Version of Python SDK to Be 5.8dev7

- pyproject.toml
> Bump to 5.8.0

- pyproject.toml
> Bump version to 5.9.0.dev1

- poetry.lock
- pyproject.toml
- requirements.txt
Update dependencies
https://dominodatalab.atlassian.net/browse/DOM-52312
> updated dependencies

- datasource_api_client/models/list_request.py
- openapi/datasource.yaml
- pyproject.toml
- tests/conftest.py
* Update page_size only
* Fix logging fixture
https://dominodatalab.atlassian.net/browse/DOM-53567
> Fix pageSize to page_size and regenerate client (#129)

- pyproject.toml
Bumped to the dev version after 5.10 is released
https://dominodatalab.atlassian.net/browse/DOM-53915
> Bumped to dev version in the main branch

- pyproject.toml
Published 5.11.0.dev1. Bumped the version to 5.11.0.dev2
https://dominodatalab.atlassian.net/browse/DOM-54988
> bumped to 5.11.0.dev2

- docs/source/index.rst
Docs should not say that this feature is in preview: https://python-docs.dominodatalab.com/en/latest/index.html
> DOM-63821 removing preview note

- pyproject.toml
Add datasets as part of the Data SDK
https://dominodatalab.atlassian.net/browse/DOM-65175
> Bump version to 6.1.0

- domino_data/vectordb.py
- tests/test_vectordb.py
dropped the support for connecting domino pinecone data source using pinecone python 2.x client.
Pinecone introduced the serverless architecture in early 2024 and sunset the legacy pod based deployments on 2025.
Some concepts present in the legacy architecture such as environment and project are not required any more when using the pinecone python client.
Environment is completely gone. The routing and scaling are fully managed behind the scene. 
Project is implicitly tied to the API key. Each API key is scoped to a single project. 
Pinecone claims that their python 2.x client is still compatible with the new serverless architecture. However for it to be integrated with Domino data source, we depend on the environment and project configuration to be able to reverse proxy the requests. …
> dropped the support for connecting domino pinecone data source using pinecone python 2.x client

- pyproject.toml
bumped version to 6.1.1
https://dominodatalab.atlassian.net/browse/DOM-66808
> bumped version to 6.1.1

- pyproject.toml
Update version to be published to be 6.3.0 to incorporate latest changes that add datetime precision to relational Data Sources.
https://dominodatalab.atlassian.net/browse/OT-68514
> [DOM-68514] Update domino-data version to 6.3.0

- datasource_api_client/models/datasource_dto_auth_type.py
- openapi/datasource.yaml
Update data services submodule to include key pair authentication for Snowflake Data Source.
https://dominodatalab.atlassian.net/browse/DOM-69994
> [DOM-69993] Update data services to include key pair authentication for Snowflake

- pyproject.toml
> DOM-70594 bumping version to 6.5.0
