dominodatalab/domino-data

.github/workflows/build.yml, domino_data/data_sources.py, tests/test_datasource.py
Config objects weren't imported properly since they move to `configuration_gen`
https://dominodatalab.atlassian.net/browse/DOM-38900
=> Override import to find configs

domino_data/training_sets/client.py, tests/test_datasource.py
When creating training set version with name that already exists in a different project, stack trace is not informative and only says `could not create Training Set Version`. Fix is to surface the exception thrown by domino.
- [x ] 🔧 Bug fix (non-breaking change which fixes an issue)
=> More informative stack trace message when training set version cannot be created

Makefile, domino_data/data_sources.py
When user instantiates DataSourceClient in the remote data plane, a logging error will be displayed like this: 
https://dominodatalab.atlassian.net/browse/DOM-42475
- [] 🥂 Improvement (non-breaking change which improves an existing feature)
=> [DOM-42475] Adding error message when user accesses SDK from remote data plane

domino_data/_feature_store/sync.py
Feature store sync script fix for using Git SSH credentials
https://dominodatalab.atlassian.net/browse/DOM-43054
The sync script fails to run in the Domino job because the interactive question for host check can't be answered
=> fix for using git SSH credentials

domino_data/_feature_store/git.py, domino_data/_feature_store/logging.py, domino_data/_feature_store/run.py, domino_data/_feature_store/sync.py, domino_data/logging.py, tests/feature_store/test_logging.py
The logging filter doesn't work well with exception logs.  Feature store exception logs can't be logged to the console.  We need logs to console so that it will be captures as job run result. So created a dedicated logger for feature store. 
https://dominodatalab.atlassian.net/browse/DOM-43059
=> Fix for missing feature store error logs

poetry.lock, pyproject.toml
PR to fix a vulnerability with gitpython@3.1.29
```
Vulnerability found in gitpython version 3.1.29
Vulnerability ID: 52322
Affected spec: <3.1.30
ADVISORY: Gitpython 3.1.30 includes a fix for CVE-2022-24439:
Gitpython is vulnerable to Remote Code Execution (RCE) due to improper user
input validation, which makes it possible to inject a maliciously crafted
remote URL into the clone command. Exploiting this vulnerability is possible
because the library makes external calls to git without sufficient
sanitization of input arguments.
CVE-2022-24439
For more information, please visit https://pyup.io/v/[52](https://github.com/dominodatalab/domino-data/actions/runs/3942747608/jobs/6746760375#step:10:53)322/f17
```
=> Update gitpython to 3.1.30

domino_data/data_sources.py
Increase timeout to avoid issues when using Data SDK in compute clusters
https://dominodatalab.atlassian.net/browse/DOM-43367
=> Increase timeout to Nucleus from 5 to 20s

domino_data/data_sources.py
Removing beta messaging from sdk on instantiation of datasource_client. Will be removing environment variable from nucleus next:)
Shouldn't go in 5.5 release FYI
https://dominodatalab.atlassian.net/browse/DOM-42841
Do it!
=> DOM-42841 Removing beta messaging on datasource_client instantiation

domino_data/data_sources.py
Domino is going away from using "beta", switching to "Preview"
https://dominodatalab.atlassian.net/browse/DOM-44561
=> DOM-44561 Changing from "beta" to "Preview"

domino_data/_feature_store/client.py, domino_data/_feature_store/sync.py, feature_store_api_client/models/__init__.py, feature_store_api_client/models/feature.py, feature_store_api_client/models/feature_tags.py, feature_store_api_client/models/feature_view_request.py, feature_store_api_client/models/upsert_feature_views_request.py, openapi/featurestore.yaml
Added more Feature view fields
https://dominodatalab.atlassian.net/browse/DOM-43536
=> add more feature view fields

domino_data/data_sources.py
Improved error handling while getting data sources. 
https://dominodatalab.atlassian.net/browse/DOM-48640
=> Improved error handling

openapi/datasource.yaml
update the git submodule and regenerate the code.
Update the git submodule and add the missing auth type
https://dominodatalab.atlassian.net/browse/DOM-48882
=> update the git submodule

domino_data/auth.py, domino_data/data_sources.py, domino_data/meta.py
DataSource Audit Trail: need to pass environment variable runId to proxy. Do it from _release-5.7_
Merge it :)
=> DataSource Audit: pass run_id from env variable

domino_data/auth.py, tests/feature_store/test_sync.py
When authenticating with data source proxy service, the jwt token takes precedence over the api key.
https://dominodatalab.atlassian.net/browse/DOM-49784
=> changed the order of choosing authentication fields

datasource_api_client/models/list_request.py, openapi/datasource.yaml, tests/conftest.py
Parameter page_size using camel case in the backend but not in the client.
https://dominodatalab.atlassian.net/browse/DOM-53567
=> Fix pageSize to page_size and regenerate client

domino_data/vectordb.py, tests/test_vectordb.py
Added two functions wrapping the parameters to initialize the Pinecone client and target the index for Pinecone 3.x python client with Domino data source
https://dominodatalab.atlassian.net/browse/DOM-54988
=> Functions to simplify Pinecone 3x client API parameters with Domino

domino_data/data_sources.py, pyproject.toml
Fix the wrong default domino run id when getting the data source.  
This was introduced when fixing the build issue when generating the client using a particular version of open api generator.  Fortunately, the final generated code doesn't require a default value to be present to pass the build. 
https://dominodatalab.atlassian.net/browse/DOM-57725
=> Fix the get datasource issue with no run id

domino_data/data_sources.py
the listObjectsV2 AWS API returns subdirectories as separate objects in the list of objects returned, but we omit them from the list returned to the user. 
We should keep these entries in the list returned to the user since this will cause page_size parameter to appear incorrect. I also think it's important to keep the same behavior as the native API (and boto3 API has the same behavior)
=> DOM-63173 keeping subdirectories in the list returned

domino_data/data_sources.py, pyproject.toml
Port the fix of domino run id from 5.11 to the main branch 
Fix the wrong default domino run id when getting the data source.  
https://dominodatalab.atlassian.net/browse/DOM-57725
https://dominodatalab.atlassian.net/browse/DOM-62827
=> Fix the get datasource issue with no run id (#147)

docs/source/domino_data.rst
Need to remove preview note from this docs page: https://python-docs.dominodatalab.com/en/latest/domino_data.html
=> DOM-63821 removing "preview" from docs

domino_data/datasets.py, tests/cassettes/test_dataset/test_config_override.yaml, tests/test_dataset.py
https://dominodatalab.atlassian.net/browse/DOM-67034
=> [DOM-67034] Add support for overriding dataset config
